AWSTemplateFormatVersion: "2010-09-09"
Description: "This template creates EC2 Instance"
Resources: 
  Bastion:                            # Logical Name or Logical ID. Logical ID has to be unique within your temple 
    Type: "AWS::EC2::Instance"               # Key and Value is Reserved (Pre Define by AWS)
    Properties:                              # defines all details (what security group, what type of Instance, load balncer, EBS volume) 
      ImageId: "ami-0beaa649c482330f7"
      InstanceType: "t2.micro"
      KeyName: "WindowsKey"
      SecurityGroupIds: 
        - !Ref MySecurityGroup    # Reference to the resource, Reference to the Logical ID


  
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Bastion-sg
      GroupDescription: Security group for my Bastion Instances
      VpcId: "vpc-0166d49255c12d353"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/24
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/32
       
      